---
title: "AEET_2015_abstract"
author: "Pérez-Luque AJ, Zamora R and Bonet FJ"
output: 
  md_document:
    variant: markdown_github
---

### Colonization pattern of Quercus pyrenaica in mediterranean abandoned croplands: a study case from Sierra Nevada (Spain)

**Pérez-Luque AJ, Zamora R and Bonet FJ** 

Land abandonment is a major global change driver in the Mediterranean Region where anthropic activity has played an important role shaping landscape configuration. Understanding the woodland expansion towards marginal areas (abandoned crops) is critical to develop effective management strategies. 

In this work we analyze the colonization pattern of abandoned croplands by *Quercus pyrenaica* in Sierra Nevada. We aimed to assess differences among populations in the rear edge of its distribution. For this purpose we characterized *(i)* the colonization pattern of *Q. pyrenaica*, *(ii)* the structure of the seed source (mature forest), and *(iii)* the abundance of the main seed disperser (European jay, *Garrulus glandarius*). 

The study was conducted in five abandoned croplands located in two representative populations of *Q. pyrenaica* located in contrasting slopes. We sampled three habitat types: mature forest, edge-forest and abandoned cropland. A total of 83 plots (10 x 30 m) were sampled. In each plot all tree individuals were counted. Basal diameter and height of each tree specimen were measured and sapling abundance was calculated. Abundance of European jay was determined by bird census (7-year) (line-transect method). 

Sapling abundance was different between northern and southern *Q. pyrenaica* populations. However, no differences on sapling abundance were observed among habitat types. Abundance of jay does not differ significantly between sites. On the other hand, forest structure showed differences between populations. Differences in colonization pattern could be explained by different management histories and (different land-use intensities) before abandonment of the croplands (biological legacies) and cattle management practices. 
